# Generated by Django 2.2.3 on 2020-10-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_course', '0002_auto_20201011_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'verbose_name_plural': 'Catagories'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=3000),
        ),
    ]
