# Generated by Django 2.2.3 on 2020-10-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0004_auto_20201020_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenquiz',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
